CREATE VIEW [DEV_SCBSG].[XXONT_SAVE_PUMP_MISSED_V] AS
--Transaction Types based on Oracle Lookup
WITH XXOE_TRANSACTION_TYPES AS
 (SELECT (SELECT OTT.TRANSACTION_TYPE_ID
            FROM EBS.OE_TRANSACTION_TYPES_TL OTT
           WHERE OTT.NAME = 'SC EXCHANGE RETURN LINE' --FLV1.DESCRIPTION
          ) FROM_LINE_TYPE_ID,
         (SELECT OTT.TRANSACTION_TYPE_ID
            FROM EBS.OE_TRANSACTION_TYPES_TL OTT
           WHERE OTT.NAME = 'SC EXCHANGE SALE LINE' --FLV1.TAG
          ) TO_LINE_TYPE_ID
    FROM EBS.FND_LOOKUP_VALUES FLV1
   WHERE FLV1.LOOKUP_TYPE = 'SN_ONT_KDNS_EXCH_LINE_TYPE'
     AND FLV1.LOOKUP_CODE = 'REASON_CODE'
     AND FLV1.ENABLED_FLAG = 'Y'),
     
--This will be removed once FND_LOOKUP_VALUES issue is resolved
XXFND_LOOKUP_VALUES AS
 (SELECT 'SN_ONT_KDNS_EXCHANGE_ITEM' LOOKUP_TYPE,
         '10' LOOKUP_CODE,
         '122611' DESCRIPTION,
         '122613' TAG,
         'Y' ENABLED_FLAG UNION SELECT 'SN_ONT_KDNS_EXCHANGE_ITEM' LOOKUP_TYPE,
         '20' LOOKUP_CODE,
         '122612' DESCRIPTION,
         '122614' TAG,
         'Y' ENABLED_FLAG UNION SELECT 'SN_ONT_KDNS_EXCHANGE_ITEM' LOOKUP_TYPE,
         '30' LOOKUP_CODE,
         '126782' DESCRIPTION,
         '122613' TAG,
         'Y' ENABLED_FLAG UNION SELECT 'SN_ONT_KDNS_EXCHANGE_ITEM' LOOKUP_TYPE,
         '40' LOOKUP_CODE,
         '126781' DESCRIPTION,
         '122614' TAG,
         'Y' ENABLED_FLAG UNION SELECT 'SN_ONT_KDNS_EXCHANGE_ITEM' LOOKUP_TYPE,
         '50' LOOKUP_CODE,
         '922611' DESCRIPTION,
         '122613' TAG,
         'Y' ENABLED_FLAG UNION SELECT 'SN_ONT_KDNS_EXCHANGE_ITEM' LOOKUP_TYPE,
         '60' LOOKUP_CODE,
         '922612' DESCRIPTION,
         '122614' TAG,
         'Y' ENABLED_FLAG),
         
-- Pump Box level SKU which is on Ship lines    
XX_SALES_ITEMS_LOOKUP AS
 (SELECT DISTINCT MSI1.SEGMENT1 SALE_ITEM,
         MSI1.INVENTORY_ITEM_ID SALE_ITEM_ID, 
         MSI1.description sale_desc
    FROM XXFND_LOOKUP_VALUES FLV--EBS.FND_LOOKUP_VALUES FLV
    JOIN EBS.MTL_SYSTEM_ITEMS_B MSI1
      ON FLV.TAG = MSI1.SEGMENT1
    WHERE FLV.LOOKUP_TYPE = 'SN_ONT_KDNS_EXCHANGE_ITEM'
     AND FLV.ENABLED_FLAG = 'Y'   
     AND MSI1.organization_id = 101
     ),
     
-- RMA critical SKU for PUMP which is on Return lines      
XX_RETURN_ITEMS_LOOKUP AS
 (SELECT DISTINCT
         MSI2.SEGMENT1 RETURN_ITEM,
         MSI2.INVENTORY_ITEM_ID RETURN_ITEM_ID, 
         MSI2.description ret_desc
    FROM XXFND_LOOKUP_VALUES FLV--EBS.FND_LOOKUP_VALUES FLV  
    JOIN EBS.MTL_SYSTEM_ITEMS_B MSI2
      ON FLV.DESCRIPTION = MSI2.SEGMENT1
   WHERE FLV.LOOKUP_TYPE = 'SN_ONT_KDNS_EXCHANGE_ITEM'
     AND FLV.ENABLED_FLAG = 'Y'   
     AND MSI2.organization_id = 101
     ),
     
--This is to get all the exchange lines shipped after 13Dec2022 for Pump Box level SKU
XX_SALE_LINES AS
 (SELECT OOLS.HEADER_ID,
         OOLS.LINE_NUMBER,
         OOLS.LINE_ID,
         OOLS.LINE_TYPE_ID,
         OOLS.FLOW_STATUS_CODE,
         OOLS.ORDERED_ITEM,
         OOLS.ORDERED_QUANTITY,
         OOLS.ORIG_SYS_LINE_REF,
         OOLS.SCHEDULE_SHIP_DATE,
         OOLS.ATTRIBUTE4,
         OOLS.ATTRIBUTE15,
         OOLS.INVENTORY_ITEM_ID,
         OOLS.SHIP_FROM_ORG_ID,
         OOLS.CANCELLED_FLAG,
         OOLS.OPEN_FLAG,
         OOLS.LAST_UPDATE_DATE,
         OOLS.TOP_MODEL_LINE_ID,
         OOLS.ITEM_TYPE_CODE,
         OOLS.LINE_CATEGORY_CODE,
         OOLS.SHIPMENT_PRIORITY_CODE,
         XMSI.SALE_ITEM,
         XMSI.sale_desc,
         OER.REASON_CODE,
         CAST (MMT.TRANSACTION_DATE AS DATE) TRANSACTION_DATE
    FROM EBS.MTL_MATERIAL_TRANSACTIONS MMT
    JOIN XX_SALES_ITEMS_LOOKUP XMSI
      ON MMT.INVENTORY_ITEM_ID = XMSI.SALE_ITEM_ID
     AND MMT.TRANSACTION_TYPE_ID = 52 -- SO Pick
     AND MMT.SUBINVENTORY_CODE = 'FG'
     AND CAST (MMT.TRANSACTION_DATE AS DATE)>= '13-Dec-2022'
    JOIN EBS.OE_ORDER_LINES_ALL OOLS
      ON MMT.TRX_SOURCE_LINE_ID = OOLS.LINE_ID
     AND OOLS.LINE_TYPE_ID = 1006--Exchange Sale Line
     --AND OOLS.HEADER_ID = 9964548
     AND ISNULL(OOLS.SHIPMENT_PRIORITY_CODE, 'X') <> 'PAW'
     AND OOLS.FLOW_STATUS_CODE IN ('CLOSED', 'AWAITING_FULFILLMENT')
    LEFT JOIN EBS.OE_REASONS OER
      ON OER.ENTITY_ID = OOLS.LINE_ID
     AND OER.ENTITY_CODE = 'LINE'
   WHERE 1=1
   AND (OOLS.CANCELLED_FLAG = 'N' OR
         (OOLS.CANCELLED_FLAG = 'Y' AND OER.REASON_CODE <> 'SAVE_PUMP'))),

--This is to get all the return lines for the order having exchange sales lines
XX_RETURN_LINES AS
(SELECT OOLR.HEADER_ID, OOLR.LINE_ID, OOLR.INVENTORY_ITEM_ID,
XFLI.RETURN_ITEM
                FROM EBS.OE_ORDER_LINES_ALL OOLR
                JOIN XX_RETURN_ITEMS_LOOKUP XFLI
      ON OOLR.INVENTORY_ITEM_ID = XFLI.RETURN_ITEM_ID
    LEFT JOIN EBS.OE_REASONS OER
      ON OER.ENTITY_ID = OOLR.LINE_ID
     AND OER.ENTITY_CODE = 'LINE'
   WHERE OOLR.LINE_TYPE_ID = 1005 --Exchange Return Line
     AND (OOLR.CANCELLED_FLAG = 'N' OR
         (OOLR.CANCELLED_FLAG = 'Y' AND OER.REASON_CODE <> 'SAVE_PUMP'))
     AND ISNULL(OOLR.SHIPMENT_PRIORITY_CODE, 'X') <> 'PAW'
     AND OOLR.FLOW_STATUS_CODE IN ('CLOSED', 'AWAITING_FULFILLMENT')
     AND EXISTS (SELECT 1 FROM XX_SALE_LINES XXSL WHERE XXSL.HEADER_ID = OOLR.HEADER_ID)),
     
     
--This is to get the missed opportunity where we have both sales and return lines in same order
XXOE_ORDER_DTLS_S1 AS
 (SELECT MP.ORGANIZATION_ID SHIP_FROM_ORG_ID,
         MP.ORGANIZATION_CODE SHIP_FROM,
         OOHA.HEADER_ID,
         XSL.LINE_ID,
         OOHA.ORDER_NUMBER,
         OOHA.FLOW_STATUS_CODE ORDER_STATUS,
         XSL.LINE_NUMBER,
         XSL.FLOW_STATUS_CODE LINE_STATUS,
         XSL.INVENTORY_ITEM_ID,
         XSL.SALE_ITEM,
         XSL.SALE_desc,
         MIC_OM.SEGMENT2 OM_CATEGORY,
        -- XSL.INVENTORY_CATEGORY,
         XSL.ATTRIBUTE4 MARKET,
         CO.ITEM_COST,
         (CO.ITEM_COST * XSL.ORDERED_QUANTITY) TOTAL_COST,
         XSL.ORDERED_QUANTITY,
         XSL.CANCELLED_FLAG KDNS_CANCELLATION,
         (CASE
           WHEN XSL.CANCELLED_FLAG = 'Y' THEN
            XSL.LAST_UPDATE_DATE
           ELSE
            NULL
         END) CANCELLATION_DATE,
         XSL.REASON_CODE CANCELLATION_REASON,
         NULL MATTRESS_CANCELLED,
         XSL.LINE_TYPE_ID,
         'Exchange Sale' LINE_TYPE,
         XSL.SCHEDULE_SHIP_DATE,
         '' ORDER_DELIVERED,
         XSL.TRANSACTION_DATE ACTUAL_SHIPMENT_DATE,
         '' SHIPPING_STATUS,
         XSL.ITEM_TYPE_CODE,
         XSL.LINE_CATEGORY_CODE,
         XSL.OPEN_FLAG
    FROM XX_SALE_LINES XSL
    JOIN EBS.OE_ORDER_HEADERS_ALL OOHA
      ON OOHA.HEADER_ID = XSL.HEADER_ID
  JOIN PROD_SCBSG.MTL_ITEM_CATEGORIES_V MIC_OM
      ON XSL.INVENTORY_ITEM_ID = MIC_OM.INVENTORY_ITEM_ID
     AND XSL.SHIP_FROM_ORG_ID = MIC_OM.ORGANIZATION_ID
     AND MIC_OM.CATEGORY_SET_NAME = 'SC OM Category'
    JOIN EBS.MTL_PARAMETERS MP
      ON XSL.SHIP_FROM_ORG_ID = MP.ORGANIZATION_ID
    JOIN EBS.CST_ITEM_COSTS CO
      ON XSL.INVENTORY_ITEM_ID = CO.INVENTORY_ITEM_ID
     AND XSL.SHIP_FROM_ORG_ID = CO.ORGANIZATION_ID
     AND CO.COST_TYPE_ID = 1
   WHERE 1 = 1
     AND XSL.TOP_MODEL_LINE_ID IS NOT NULL
     AND EXISTS (SELECT 1
                FROM XX_RETURN_LINES XRL, XXFND_LOOKUP_VALUES XFLV
               WHERE XRL.HEADER_ID = XSL.HEADER_ID
         AND XFLV.LOOKUP_TYPE = 'SN_ONT_KDNS_EXCHANGE_ITEM'
     AND XFLV.ENABLED_FLAG = 'Y'
   AND XFLV.TAG = XSL.SALE_ITEM
   AND XFLV.DESCRIPTION = XRL.RETURN_ITEM
     )),
     
 XXOE_ORDER_DTLS_S2 AS
(SELECT MP.ORGANIZATION_ID SHIP_FROM_ORG_ID,
         MP.ORGANIZATION_CODE SHIP_FROM,
         OOHA.HEADER_ID,
         XSL.LINE_ID,
         OOHA.ORDER_NUMBER,
         OOHA.FLOW_STATUS_CODE ORDER_STATUS,
         XSL.LINE_NUMBER,
         XSL.FLOW_STATUS_CODE LINE_STATUS,
         XSL.INVENTORY_ITEM_ID,
         XSL.sale_item,
         XSL.sale_desc,
         MIC_OM.SEGMENT2 OM_CATEGORY,
         XSL.ATTRIBUTE4 MARKET,
         CO.ITEM_COST,
         (CO.ITEM_COST * XSL.ORDERED_QUANTITY) TOTAL_COST,
         XSL.ORDERED_QUANTITY,
         XSL.CANCELLED_FLAG KDNS_CANCELLATION,
         (CASE
           WHEN XSL.CANCELLED_FLAG = 'Y' THEN
            XSL.LAST_UPDATE_DATE
           ELSE
            NULL
         END) CANCELLATION_DATE,
         XSL.REASON_CODE CANCELLATION_REASON,
         NULL MATTRESS_CANCELLED,
         XSL.LINE_TYPE_ID,
         'Exchange Sale' LINE_TYPE,
         XSL.SCHEDULE_SHIP_DATE,
         '' ORDER_DELIVERED,
         XSL.TRANSACTION_DATE ACTUAL_SHIPMENT_DATE,
         '' SHIPPING_STATUS,
         XSL.ITEM_TYPE_CODE,
         XSL.LINE_CATEGORY_CODE,
         XSL.OPEN_FLAG
    FROM XX_SALE_LINES XSL
    JOIN EBS.OE_ORDER_HEADERS_ALL OOHA
      ON OOHA.HEADER_ID = XSL.HEADER_ID -- scenario 1 + Scenario 2
    JOIN PROD_SCBSG.MTL_ITEM_CATEGORIES_V MIC_OM
      ON XSL.INVENTORY_ITEM_ID = MIC_OM.INVENTORY_ITEM_ID
     AND XSL.SHIP_FROM_ORG_ID = MIC_OM.ORGANIZATION_ID
     AND MIC_OM.CATEGORY_SET_NAME = 'SC OM Category'
    JOIN EBS.MTL_PARAMETERS MP
      ON XSL.SHIP_FROM_ORG_ID = MP.ORGANIZATION_ID
    JOIN EBS.CST_ITEM_COSTS CO
      ON XSL.INVENTORY_ITEM_ID = CO.INVENTORY_ITEM_ID
     AND XSL.SHIP_FROM_ORG_ID = CO.ORGANIZATION_ID
     AND CO.COST_TYPE_ID = 1
   WHERE 1 = 1
     AND NOT EXISTS (SELECT 1
                FROM EBS.OE_ORDER_LINES_ALL OLA, XX_RETURN_ITEMS_LOOKUP RSI
               WHERE OLA.HEADER_ID = XSL.HEADER_ID
               AND OLA.LINE_TYPE_ID = 1005--Exchange Return Line
               AND OLA.CANCELLED_FLAG <> 'Y'
               AND OLA.INVENTORY_ITEM_ID = RSI.RETURN_ITEM_ID
               ) -- Condition to filter out scenario 1
     AND EXISTS (SELECT 'Y' FROM EBS.OE_ORDER_LINES_ALL OOL_top, ebs.oe_order_headers_all ooh_orig
     , ebs.oe_order_lines_all ool_orig
           WHERE OOL_TOP.HEADER_ID = XSL.HEADER_ID
             AND OOL_TOP.LINE_TYPE_ID = 1022 -- Credit Only
             AND OOL_TOP.CANCELLED_FLAG <> 'Y'
             AND OOL_TOP.ATTRIBUTE15 IS NOT NULL
             AND ooh_orig.order_number = SUBSTRING(OOL_TOP.ATTRIBUTE15, 1, 11)
             AND ooh_orig.header_id = ool_orig.header_id
             and ool_orig.line_number =  TRIM (SUBSTRING(OOL_TOP.ATTRIBUTE15, 14, 17))
             and ool_orig.line_type_id = 1002
             and ool_orig.inventory_item_id = xsl.inventory_item_id
             )) -- Original Order Number / Line Number  
     
--MAIN SQL
--1st scenario
select 'Scenario1' Scenario,ORD_DTL_S1.SHIP_FROM_ORG_ID,
       ORD_DTL_S1.SHIP_FROM,
       ORD_DTL_S1.HEADER_ID,
       ORD_DTL_S1.LINE_ID,
       ORD_DTL_S1.ORDER_NUMBER,
       ORD_DTL_S1.ORDER_STATUS,
       ORD_DTL_S1.LINE_NUMBER,
       ORD_DTL_S1.LINE_STATUS,
       ORD_DTL_S1.INVENTORY_ITEM_ID,
       ORD_DTL_S1.SALE_ITEM ITEM_NUMBER,
       ORD_DTL_S1.SALE_desc ITEM_DESCRIPTION,
       ORD_DTL_S1.OM_CATEGORY,
       MIC.SEGMENT2 INVENTORY_CATEGORY,
       ORD_DTL_S1.MARKET,
       ORD_DTL_S1.ITEM_COST,
       ORD_DTL_S1.TOTAL_COST,
       ORD_DTL_S1.ORDERED_QUANTITY,
       ORD_DTL_S1.KDNS_CANCELLATION,
       ORD_DTL_S1.CANCELLATION_DATE,
       ORD_DTL_S1.CANCELLATION_REASON,
       ORD_DTL_S1.MATTRESS_CANCELLED,
       ORD_DTL_S1.LINE_TYPE_ID,
       ORD_DTL_S1.LINE_TYPE,
       ORD_DTL_S1.SCHEDULE_SHIP_DATE,
       ORD_DTL_S1.ORDER_DELIVERED,
       ORD_DTL_S1.ACTUAL_SHIPMENT_DATE,
       ORD_DTL_S1.SHIPPING_STATUS,
       ORD_DTL_S1.ITEM_TYPE_CODE,
       ORD_DTL_S1.LINE_CATEGORY_CODE,
       ORD_DTL_S1.OPEN_FLAG
       from XXOE_ORDER_DTLS_S1 ORD_DTL_S1, PROD_SCBSG.MTL_ITEM_CATEGORIES_V MIC
   WHERE MIC.CATEGORY_SET_NAME = 'SC Inventory Category'
     AND MIC.SEGMENT2 = 'PUMP FG'
     AND MIC.ORGANIZATION_ID = ORD_DTL_S1.SHIP_FROM_ORG_ID
     AND MIC.INVENTORY_ITEM_ID = ORD_DTL_S1.INVENTORY_ITEM_ID
UNION ALL
select 'Scenario2' scenario, ORD_DTL_S2.SHIP_FROM_ORG_ID,
       ORD_DTL_S2.SHIP_FROM,
       ORD_DTL_S2.HEADER_ID,
       ORD_DTL_S2.LINE_ID,
       ORD_DTL_S2.ORDER_NUMBER,
       ORD_DTL_S2.ORDER_STATUS,
       ORD_DTL_S2.LINE_NUMBER,
       ORD_DTL_S2.LINE_STATUS,
       ORD_DTL_S2.INVENTORY_ITEM_ID,
       ORD_DTL_S2.sale_item ITEM_NUMBER,
       ORD_DTL_S2.sale_desc ITEM_DESCRIPTION,
       ORD_DTL_S2.OM_CATEGORY,
       MIC.SEGMENT2 INVENTORY_CATEGORY,
       ORD_DTL_S2.MARKET,
       ORD_DTL_S2.ITEM_COST,
       ORD_DTL_S2.TOTAL_COST,
       ORD_DTL_S2.ORDERED_QUANTITY,
       ORD_DTL_S2.KDNS_CANCELLATION,
       ORD_DTL_S2.CANCELLATION_DATE,
       ORD_DTL_S2.CANCELLATION_REASON,
       ORD_DTL_S2.MATTRESS_CANCELLED,
       ORD_DTL_S2.LINE_TYPE_ID,
       ORD_DTL_S2.LINE_TYPE,
       ORD_DTL_S2.SCHEDULE_SHIP_DATE,
       ORD_DTL_S2.ORDER_DELIVERED,
       ORD_DTL_S2.ACTUAL_SHIPMENT_DATE,
       ORD_DTL_S2.SHIPPING_STATUS,
       ORD_DTL_S2.ITEM_TYPE_CODE,
       ORD_DTL_S2.LINE_CATEGORY_CODE,
       ORD_DTL_S2.OPEN_FLAG
       FROM XXOE_ORDER_DTLS_S2 ORD_DTL_S2, PROD_SCBSG.MTL_ITEM_CATEGORIES_V MIC
       WHERE 1 = 1
     AND MIC.CATEGORY_SET_NAME = 'SC Inventory Category'
     AND MIC.SEGMENT2 = 'PUMP FG'
     AND MIC.ORGANIZATION_ID = ORD_DTL_S2.SHIP_FROM_ORG_ID
     AND MIC.INVENTORY_ITEM_ID = ORD_DTL_S2.INVENTORY_ITEM_ID;